version: '3'

services:
  server:
    build: ./server
    ports:
      - "3001:3001"
    networks:
      - app-network

  client:
    build: .
    ports:
      - "80:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge